var randomNumber1= Math.floor(Math.random()*6) +1;
var randomdiceImage = "dice" + randomNumber1 + ".png"; //basically we are concatinating the name of 
//the dice with the random number generated by math.random().So if random number is 3,the image name becomes dice3 and 
// the dice3 image is selected
var randomImagesource =  randomdiceImage;

var img1 = document.querySelectorAll("img")[0];
img1.setAttribute("src",randomImagesource);

var randomNumber2= Math.floor(Math.random()*6)+1;
var randomdiceImage2 = "dice" + randomNumber2 +".png";
var randomImagesource2 = randomdiceImage2;

var img2 = document.querySelectorAll("img")[1];
img2.setAttribute("src",randomImagesource2);

if (randomNumber1>randomNumber2){
    document.querySelector("h1").innerHTML= "Luck favoured you Player 1,You Won!";

}

else if(randomNumber2>randomNumber1)
{
    document.querySelector("h1").innerHTML= "Luck favoured you Player 2,You Won!";
}
else
{
    document.querySelector("h1").innerHTML = "It's a Draw!"
}
